### ISSUE TITLE
Renovate Integration

### ISSUE THREAD

**Issue by huxuan** [serious-scaffold/ss-python#188]
Tasks:

- [x] [Update] pdm.lock (https://github.com/serious-scaffold/ss-python/pull/321)
- [x] [Pin & Update] Github Actions (https://github.com/serious-scaffold/ss-python/pull/321)
- [x] [Pin & Update] docker images in GitHub Actions. (https://github.com/serious-scaffold/ss-python/pull/321)
- [x] [Pin & Update] docker images in GitLab CI. (https://github.com/serious-scaffold/ss-python/pull/340)
- [x] <del> [Pin & Update] docker images in devcontainer dockerfile. </del> Deprecated since the base image is dynamic according to Python version.
- [x] `pdm` and `pre-commit` in devcontainer dockerfile. (https://github.com/serious-scaffold/ss-python/pull/343)
- [x] <del> #391 </del> Mark as done as tracked with a separate issue. 
- [x] [Update] Copier template.
  - [x] <del> GitHub Actions </del> Deprecated since it brings extra complexicity
  - [x] <del> GitLab CI </del> Deprecated since it bring extra complexicity
  - [x] #346
- [x] Validate Renovate config. (https://github.com/serious-scaffold/ss-python/pull/344)
- [x] <del> Group similar tasks, if applicable. </del> Deprecated as a continuous work.
- [x] <del> Unify git author. </del> Deprecated as too tricky and not reproducible.
- [x] Documentation for renovate setup. (#364)

Ref:

- For GitHub: https://github.com/renovatebot/github-action
- For GitLab: https://gitlab.com/renovate-bot/renovate-runner

**Comment by msclock** [comment]
> or `dependabot` for GitHub and `Renovate` for GitLab.

That's a great option. It make up dependency update on gitlab.

**Comment by huxuan** [comment]
> > or `dependabot` for GitHub and `Renovate` for GitLab.
> 
> That's a great option. It make up dependency update on gitlab.

Yep, I learned from your repos. Feel free to propose more ideas to make serious-scaffold-python better. :-)

**Comment by msclock** [comment]
My experience with renovate is based on the repo [renovate-runner](https://gitlab.com/renovate-bot/renovate-runner) on gitlab. Of course, official [docs](https://docs.renovatebot.com/configuration-options/) are mainly refered.

**Comment by huxuan** [comment]
Some Reference:

- https://github.com/renovatebot/renovate/issues/25556

**Comment by huxuan** [comment]
Seems all the sub-tasks have been done. 

@msclock Do you have any comments? Whether it is OK to close this issue. :-)

**Comment by msclock** [comment]
> Seems almost all the sub-tasks have been done (or deprecated or tracked with a separate issue).
> 
> @msclock Do you have any comments? Whether it is OK to close this issue. :-)

I need more time to digging if there are some applicable workarounds to fix #400.

**Comment by huxuan** [comment]
> Sorry for late reply. I need more time to digging if there are some applicable workarounds to fix #400.

That's absolutely OK, let us track that in the separate issue and I will close this one for the first bunch of renovate integration.
