### ISSUE TITLE
Why use different renovate image sources?

### ISSUE THREAD

**Issue by msclock** [serious-scaffold/ss-python#357]
There are two different revnoate images source updates:
- https://github.com/serious-scaffold/ss-python/pull/354
- https://github.com/serious-scaffold/ss-python/pull/353

One uses renovate/renovate from docker registry and aonther uses the source from ghcr. I consider it is more manageable with the one source.🤔 Personally, I prefer to the one from docker registry.

**Comment by huxuan** [comment]
This will only happen for serious-scaffold, since generated project will use either github or gitlab (not both). ghcr is better for GitHub Actions, but maybe dockerhub is better for gitlab to avoid potential restrictions.

**Comment by msclock** [comment]
> This will only happen for serious-scaffold, since generated project will use either github or gitlab (not both). ghcr is better for GitHub Actions, but maybe dockerhub is better for gitlab to avoid potential restrictions.

The two are just identical, and I still consider one source is more managaeble.🤣 But it's ok then.

**Comment by huxuan** [comment]
Actually, I sufferred a lot about `GITHUB_TOKEN` or `GITHUB_COM_TOKEN` related issue on GitLab, so I would prefer avoid using any GitHub stuffs on GitLab.
