### ISSUE TITLE
Drop Python 3.8 support

### ISSUE THREAD

**Issue by huxuan** [serious-scaffold/ss-python#360]
While Python 3.8 is reaching its [end-of-life](https://devguide.python.org/versions/), maybe we should also consider dropping the support (at least in the generated project)? Currently the [DevContainer workflow](https://github.com/serious-scaffold/ss-python/actions/workflows/devcontainer.yml) is failed due to [Python 3.8 compatibility issue](https://github.com/serious-scaffold/ss-python/actions/runs/8134765480/job/22228202923), and it needs extra hack to fix.

More evidence:

1. [Sphinx 7.2.0](https://www.sphinx-doc.org/en/master/changes.html#release-7-2-0-released-aug-17-2023) already drop Python 3.8 support on Aug 17, 2023.
2. [pre-commit v3.6.0](https://github.com/pre-commit/pre-commit/releases/tag/v3.6.0) alreay drop support for python<3.9 on Dec 10, 2023.

**Comment by huxuan** [comment]
@msclock Any comments?

**Comment by msclock** [comment]
> @msclock Any comments?

I consider Python 3.8 is not up to the end of life  to security and has not escaped developer selection. Moreover, the scaffold has not yet released a maintainable version. Is the pdm support to resolve the conflicts?

Importantly, why is it not a breaking change when dropping python version support.Ideally, when a breaking change happends, the major version increment can ensure the following fixes and patches more maintainable release. So I really think it needs to consider carefully.

**Comment by huxuan** [comment]
> the scaffold has not yet released a maintainable version.

Actually, this is also one point for me, since the project is still in alpha stage, and there is only half a year remaining for Python 3.8, maybe it is more ease to propose this breaking change.

> Is the pdm support to resolve the conflicts?

Hack are needed in the DevContainer Dockerfile and with that hack, we will lose the renovate update, I will propose a back-compatible hack later.

> Importantly, why is it not a breaking change when dropping python version support.Ideally, when a breaking change happends, the major version increment can ensure the following fixes and patches having more maintainable release. So I really think it needs to consider carefully.

Gotcha, thanks for your reminder.

**Comment by msclock** [comment]
> > the scaffold has not yet released a maintainable version.
> 
> Actually, this is also one point for me, since the project is still in alpha stage, and there is only half a year remaining for Python 3.8, maybe it is more ease to propose this breaking change.
> 
> > Is the pdm support to resolve the conflicts?
> 
> Hack are needed in the DevContainer Dockerfile and with that hack, we will lose the renovate update, I will propose a back-compatible hack later.
> 
> > Importantly, why is it not a breaking change when dropping python version support.Ideally, when a breaking change happends, the major version increment can ensure the following fixes and patches having more maintainable release. So I really think it needs to consider carefully.
> 
> Gotcha, thanks for your reminder.

**Comment by huxuan** [comment]
> If it is urgent, the pr also is fine. But it might require a backfoward compatibility later. And it should ensure a minor change at least.🤣

It is absolutely not urgent, but a compatibility strategy. Another question could be, why does `sphinx` drop Python 3.8 support so early, even before Python 3.12 is released.
