### ISSUE TITLE
Invalid user accout referred by commits in commits history.

### ISSUE THREAD

**Issue by msclock** [serious-scaffold/ss-python#400]
This email is invalid causing the invalid commits history:

https://github.com/serious-scaffold/ss-python/blob/d394dcd21093ccf9f4b9ea0f9a48a4d50f77f15a/.github/workflows/renovate.yml#L11

![image](https://github.com/serious-scaffold/ss-python/assets/43399351/95c303fd-614e-441c-888b-17a897d47c25)

I consider it could use users.noreply.github.com for Renovate GitHub Bot.

**Comment by huxuan** [comment]
Actually, I created a sub-task `Unify git author` under https://github.com/serious-scaffold/ss-python/issues/188 but mark it as deprecated mostly because the same behavior is not reproducible to template users since it need a specific user id for the GitHub App as metioned here: https://github.com/orgs/community/discussions/24664. Do you have any ideas to make it happen?

**Comment by msclock** [comment]
> Actually, I created a sub-task `Unify git author` under #188 but mark it as deprecated mostly because the same behavior is not reproducible to template users since it need a specific user id for the GitHub App as metioned here: https://github.com/orgs/community/discussions/24664. Do you have any ideas to make it happen?
> 
> Currently, it shows `Co-authored-by: Renovate GitHub Bot <github@renovatebot.com>` by default which I think is kindly acceptable.
> 
> ![image](https://private-user-images.githubusercontent.com/726061/312670822-f16e2b30-1e13-4c38-93e2-ada5f74c0d8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODE4MzEsIm5iZiI6MTcxMDM4MTUzMSwicGF0aCI6Ii83MjYwNjEvMzEyNjcwODIyLWYxNmUyYjMwLTFlMTMtNGMzOC05M2UyLWFkYTVmNzRjMGQ4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQwMTU4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWExMmI1YmNlNWFhZjcyNjk1MjY4NmMwZTkwM2M0Yzk0NWIzZWY2ZDM5ZTZlYjVlMGU3NTFjMGMwNDVmZjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.db_OUqYQdirjjfOrxiciStWWn0BUWRkuamswVaxc_k4)

The point is the icon shows it is a non-existing user.

**Comment by huxuan** [comment]
> The point is the icon shows it is a non-existing user.

Yep, I definitely know that. I mean what exact username and email do you suggest and how to make it reproducible to template users.

**Comment by msclock** [comment]
I'm sure the email `41898282+<usernanme>@users.noreply.github.com` is for GitHub, such as `41898282+Renovate[Bot]@users.noreply.github.com`, but not sure what it likes on GitLab. And I'm still digging it.

**Comment by huxuan** [comment]
> I'm sure the email `41898282+<usernanme>@users.noreply.github.com` is for GitHub, such as `41898282+Renovate[Bot]@users.noreply.github.com`, but not sure what it likes on GitLab. And I'm still digging it.

The `41898282` is dynamic I think and it is not the user id for our `serious-scaffold-bot[bot]`. That is why I mean it is not reproducible to template users. Template users are supposed to create their own GitHub App as the workflow need app id and private key to work. We can definitely hard code it for our projects, but for the template users, that will not work I think.

**Comment by msclock** [comment]
> > I'm sure the email `41898282+<usernanme>@users.noreply.github.com` is for GitHub, such as `41898282+Renovate[Bot]@users.noreply.github.com`, but not sure what it likes on GitLab. And I'm still digging it.
> 
> The `41898282` is dynamic I think and it is not the user id for our `serious-scaffold-bot[bot]`. That is why I mean it is not reproducible to template users. Template users are supposed to create their own GitHub App as the workflow need app id and private key to work. We can definitely hard code it for our projects, but for the template users, that will not work I think.

> The 41898282 is dynamic I think and it is not the user id for our serious-scaffold-bot[bot]

After some digging, the id is actually the github-actions[bot] api id. See https://github.com/orgs/community/discussions/26560.

Maybe it could use as below:

```
"41898282+github-actions[bot]@users.noreply.github.com"
```

**Comment by huxuan** [comment]
> 
> After some digging, the id is actually the github-actions[bot] api id. See https://github.com/orgs/community/discussions/26560.
> 
> Maybe it could use as below:
> 
> ```
> "41898282+github-actions[bot]@users.noreply.github.com"
> ```

This just change the non-existing user to a different user that does not belong to our projects, and we will still have two authors for each commits generated by Renovate. Does this meet your expectation? Actually, there is no big differencen between them for me.

**Comment by huxuan** [comment]
> The id is essential to prevent confusing two users present in a commit. See [actions/checkout#1184](https://github.com/actions/checkout/pull/1184)

AFAIK, the pull request has to be created by the GitHub App. For us, it is `160990600+serious-scaffold-bot[bot]@users.noreply.github.com`, set `41898282+github-actions[bot]@users.noreply.github.com` as git author for Renovate will still lead to two users.

**Comment by msclock** [comment]
> > The id is essential to prevent confusing two users present in a commit. See [actions/checkout#1184](https://github.com/actions/checkout/pull/1184)
> 
> AFAIK, the pull request has to be created by the GitHub App. For us, it is `160990600+serious-scaffold-bot[bot]@users.noreply.github.com`, set `41898282+github-actions[bot]@users.noreply.github.com` as git author for Renovate will still lead to two users.

But it is better than a ghost user presents.🤣

And after digging, I'm ensure the internal users on gitlab is a preference. The configuration on GitLab shows here:
https://github.com/serious-scaffold/ss-python/blob/d394dcd21093ccf9f4b9ea0f9a48a4d50f77f15a/.gitlab/workflows/renovate.yml#L19

It could use the configuration "Renovate GitLab Bot <Renovate GitLab Bot@noreply.gitlab.com>" according to the references:
- https://docs.gitlab.com/ee/development/internal_users.html
- https://docs.gitlab.com/ee/user/group/settings/group_access_tokens.html#bot-users-for-groups
- https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html#bot-users-for-projects.
- https://forum.gitlab.com/t/project-access-tokens-what-is-the-bot-accounts-mail-address-domain-on-gitlab-saas/68165

**Comment by msclock** [comment]
> > > The id is essential to prevent confusing two users present in a commit. See [actions/checkout#1184](https://github.com/actions/checkout/pull/1184)
> > 
> > 
> > AFAIK, the pull request has to be created by the GitHub App. For us, it is `160990600+serious-scaffold-bot[bot]@users.noreply.github.com`, set `41898282+github-actions[bot]@users.noreply.github.com` as git author for Renovate will still lead to two users.
> 
> But it is better than a ghost user presents.🤣
> 
> And after digging, I'm ensure the internal users on gitlab is a preference. The configuration on GitLab shows here:
> 
> https://github.com/serious-scaffold/ss-python/blob/d394dcd21093ccf9f4b9ea0f9a48a4d50f77f15a/.gitlab/workflows/renovate.yml#L19
> 
> It could use the configuration "Renovate GitLab Bot <Renovate GitLab [Bot@noreply.gitlab.com](mailto:Bot@noreply.gitlab.com)>" according to the references:
> 
> * https://docs.gitlab.com/ee/development/internal_users.html
> * https://docs.gitlab.com/ee/user/group/settings/group_access_tokens.html#bot-users-for-groups
> * https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html#bot-users-for-projects.
> * https://forum.gitlab.com/t/project-access-tokens-what-is-the-bot-accounts-mail-address-domain-on-gitlab-saas/68165

If it's ok, I would like to make a pr to adapt the issue fix.

**Comment by huxuan** [comment]
> If it's ok, I would like to make a pr to adapt the issue fix.

It is definitely OK, both for the GitHub and GitLab, I would suggest to have a demo branch to ensure the actual result meets the expectation.

**Comment by huxuan** [comment]
> 
> And after digging, I'm ensure the internal users on gitlab is a preference. The configuration on GitLab shows here:
> 
> https://github.com/serious-scaffold/ss-python/blob/d394dcd21093ccf9f4b9ea0f9a48a4d50f77f15a/.gitlab/workflows/renovate.yml#L19
> 
> It could use the configuration "Renovate GitLab Bot <Renovate GitLab [Bot@noreply.gitlab.com](mailto:Bot@noreply.gitlab.com)>" according to the references:
> 
> * https://docs.gitlab.com/ee/development/internal_users.html
> * https://docs.gitlab.com/ee/user/group/settings/group_access_tokens.html#bot-users-for-groups
> * https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html#bot-users-for-projects.
> * https://forum.gitlab.com/t/project-access-tokens-what-is-the-bot-accounts-mail-address-domain-on-gitlab-saas/68165

For GitLab, IMO, it becomes a more complicated problem.

Firstly, the template users can use either "Group Access Token", "Project Access Token" or "Personal Access Token". And they will lead to different types of users when creating the merge request, so it will not be easy to have an email for all these situations unless we make all these as template configuration.

Moreover, take "Personal Access Token" for example, we need to know the username and email for the account which is used to generate the token, and that may not be the same person who triggers the pipeline, a.k.a. the owner of the scheduled pipeline. For Group and Project Access Token, we also need to fetch the group id or project id which will make the whole process more complicated.

**Comment by msclock** [comment]
> > And after digging, I'm ensure the internal users on gitlab is a preference. The configuration on GitLab shows here:
> > https://github.com/serious-scaffold/ss-python/blob/d394dcd21093ccf9f4b9ea0f9a48a4d50f77f15a/.gitlab/workflows/renovate.yml#L19
> > 
> > It could use the configuration "Renovate GitLab Bot <Renovate GitLab [Bot@noreply.gitlab.com](mailto:Bot@noreply.gitlab.com)>" according to the references:
> > 
> > * https://docs.gitlab.com/ee/development/internal_users.html
> > * https://docs.gitlab.com/ee/user/group/settings/group_access_tokens.html#bot-users-for-groups
> > * https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html#bot-users-for-projects.
> > * https://forum.gitlab.com/t/project-access-tokens-what-is-the-bot-accounts-mail-address-domain-on-gitlab-saas/68165
> 
> For GitLab, IMO, it becomes a more complicated problem.
> 
> Firstly, the template users can use either "Group Access Token", "Project Access Token" or "Personal Access Token". And they will lead to different types of users when creating the merge request, so it will not be easy to have an email for all these situations unless we make all these as template configuration.
> 
> Moreover, take "Personal Access Token" for example, we need to know the username and email for the account which is used to generate the token, and that may not be the same person who triggers the pipeline. For Group and Project Access Token, we also need to fetch the group id or project id (and the random string, as shown in the documentation you mentioned and the following screenshot) which is simliar to the user id of GitHub App. This will definitely make the whole process more complicated.
> 
> ![image](https://private-user-images.githubusercontent.com/726061/312707810-1a9dbf62-443d-48c9-87e4-8f945332dbee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTI0NTEsIm5iZiI6MTcxMDQxMjE1MSwicGF0aCI6Ii83MjYwNjEvMzEyNzA3ODEwLTFhOWRiZjYyLTQ0M2QtNDhjOS04N2U0LThmOTQ1MzMyZGJlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxMDI5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmIyZDNiMzQ3N2U1ODYzNDA0MTMzY2QwYmIxOWIyZTUxNDNhN2Y0ODYwODFmZDlkYjM4YmFlNzVhYzZkOGRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hGGhn5yn_e1YLTaBzp_XazHFZlpU-rY2tshXhMOHovU)
> 
> All these above have not taken self managed GitLab instance into consideration.

the situation is truly complicated seems what we can do is to proxy the variable RENOVATE_GIT_AUTHOR and require the project/group Maintenainers choose to apply the kind of tokens on gitlab. And the same things seem to do so too.😅

**Comment by huxuan** [comment]
Good point, so we can have the `github@reonvatebot.com` and `gitlab@renovatebot.com` as the default value, since it is configurable via environment variables which is natively supported by renovate.

If I understand correctly, there are several things we can do:

- Pass through the env `RENOVATE_GIT_AUTHOR` to containerized jobs in GitHub Actions since GitHub Actions do not native do that.
- Modify renovate workflow for GitHub Actions and GitLab CI/CD to ensure the fallback logic of default value.
- Document about the optional configuration `RENOVATE_GIT_AUTHOR`.
- Set an **organization** variable `RENOVATE_GIT_AUTHOR` to `serious-scaffold[bot] <160990600+serious-scaffold[bot]@users.noreply.github.com>` for the `serious-scaffold` GitHub Org.
- [Optional] Set an **group** variable `RENOVATE_GIT_AUTHOR` for the `serious-scaffold` GitLab Group.

Any comments or suggestions are welcome! :-)

**Comment by huxuan** [comment]
Inspired by the previews disuccsion, I created an issue here: https://github.com/actions/create-github-app-token/issues/114, and according to the suggestions, I made a pull request here: https://github.com/serious-scaffold/ss-python/pull/408

It seems to work but only solve the problem for GitHub App authentication on GitHub Actions. More investigation are needed.

**Comment by msclock** [comment]
> Good point, so we can have the `github@reonvatebot.com` and `gitlab@renovatebot.com` as the default value, since it is configurable via environment variables which is natively supported by renovate.
> 
> If I understand correctly, there are several things we can do:
> 
> * Pass through the env `RENOVATE_GIT_AUTHOR` to containerized jobs in GitHub Actions since GitHub Actions do not native do that.
> * Modify renovate workflow for GitHub Actions and GitLab CI/CD to ensure the fallback logic of default value.
> * Document about the optional configuration `RENOVATE_GIT_AUTHOR`.
> * Set an **organization** variable `RENOVATE_GIT_AUTHOR` to `serious-scaffold[bot] <160990600+serious-scaffold[bot]@users.noreply.github.com>` for the `serious-scaffold` GitHub Org.
> * [Optional] Set an **group** variable `RENOVATE_GIT_AUTHOR` for the `serious-scaffold` GitLab Group.
> 
> Any comments or suggestions are welcome! :-)

Anyway, a ghost user in commits history on GitHub can be prevented by configuring one env.

On ther other hand, it is needs more tricky steps on GitLab. After digging, it seems we can get the email through the GitLab [API](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html) to do the same things as actions/create-github-app-token for configuring the above env RENOVATE_GIT_AUTHOR as `Renovate[Bot] <project_55404269_bot_4df83adbd4d10149bb058439994b4e6d@noreply.gitlab.com>`.🤷‍♂️ I do know if it's worthy.

```bash
curl --header "PRIVATE-TOKEN: <a token here>" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/members" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   474  100   474    0     0    313      0  0:00:01  0:00:01 --:--:--   313
[
  {
    "id": 20313021,
    "username": "project_55404269_bot_4df83adbd4d10149bb058439994b4e6d",
    "name": "Renovate Token",
    "state": "active",
    "locked": false,
    "avatar_url": "https://secure.gravatar.com/avatar/3c54e83e2bdba6b6a86e5cce0d363718d64eec3154cc5a45a76254255667daac?s=80&d=identicon",
    "web_url": "https://gitlab.com/project_55404269_bot_4df83adbd4d10149bb058439994b4e6d",
    "access_level": 30,
    "created_at": "2024-02-29T05:53:11.437Z",
    "expires_at": "2024-03-30",
    "membership_state": "active"
  }
]
```

**Comment by huxuan** [comment]
> 🤷‍♂️ I do know if it's worthy.

Yep, that is the key point. As a workflow/pipeline that will regularly triggerred, it might not be worthy to make an additional request for each time. Even the pull request https://github.com/serious-scaffold/ss-python/pull/408 I proposed is optional, it is more like a hack rather than solution.

> Anyway, a ghost user in commits history on GitHub can be prevented by configuring one env.

I may suggest to keep a simple solution: Make the `RENOVATE_GIT_AUTHOR` configurable and provide a default hard-coded value even if it is a non-existing user.

**Comment by msclock** [comment]
> > 🤷‍♂️ I do know if it's worthy.
> 
> Yep, that is the key point. As a workflow/pipeline that will regularly triggerred, it might not be worthy to make an additional request for each time. Even the pull request #408 I proposed is optional, it is more like a hack rather than solution.
> 
> > Anyway, a ghost user in commits history on GitHub can be prevented by configuring one env.
> 
> I may suggest to keep a simple solution: Make the `RENOVATE_GIT_AUTHOR` configurable and provide a default hard-coded value even if it is a non-existing user.

Have to agree it.

**Comment by msclock** [comment]
@huxuan As discussed at #416, Besides of the configurable variable RENOVATE_GIT_AUTHOR, a notification should be sent to maintainers.

If I don't make a missing understanding, we reach the aggrement the configured RENOVATE_GIT_AUTHOR and a notification is the final solution.
