### ISSUE TITLE
Semantic release unable to push protected tags

### ISSUE THREAD

**Issue by huxuan** [serious-scaffold/ss-python#554]
https://github.com/serious-scaffold/ss-python/actions/runs/9123893292/job/25088369603

Reference:
  - https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules#about-tag-protection-rules
  - https://github.com/orgs/community/discussions/10906#discussioncomment-9466718

**Comment by huxuan** [comment]
Hi @msclock, do you have any ideas on this?

**Comment by msclock** [comment]
>  any ideas on this

@huxuan I have not set any tag protection rules before, but it seems it requires a proper permission to push tags.

the solutions come to mind are:
- loose the tag rules.
- give an access to tags for bot account.
- use PAT. 

And I prefer to option 1 or option 2.

**Comment by huxuan** [comment]
> - give an access to tags for bot account.


Do you know how to set the permission?

**Comment by msclock** [comment]
> > * give an access to tags for bot account.
> 
> Do you know how to set the permission?

Sorry it is out of my knowledge. It needs to investigate.

**Comment by msclock** [comment]
@huxuan I have checked the ss-python bot permissions which has already satisfied.

I consider the reason it failed is the permission token setup for checkout action.

**Comment by huxuan** [comment]
Wow, buddy, you saved my day!

I looked through a related reference [here](https://github.com/actions/create-github-app-token/discussions/75#discussioncomment-7469758), but ignored it since it is for protected branches rather than tags. It turns out they are the same thing.

Thanks sooooo much!
