### ISSUE TITLE
Restrict semantic-release strategy.

### ISSUE THREAD

**Issue by huxuan** [serious-scaffold/ss-python#631]
Make new version release more serious. Maybe the default config is good enough?

**Comment by msclock** [comment]
> the default config

actually, the default release config contains these  release workflows: master channel(master/main), multiple channels(x.x.x) and pre release channels(alpha, beta). We just apply the first.

The default commit convention can trigger a release seems it conforms to Angela style(l'm not very confirmed)?

**Comment by huxuan** [comment]
> actually, the default release config contains these release workflows: master channel(master/main), multiple channels(x.x.x) and pre release channels(alpha, beta). We just apply the first.

Yep, we already use the default configuration for `branches`, it just seems to work.

> The default commit convention can trigger a release seems it conforms to Angela style(l'm not very confirmed)?

Yep, the `preset` should be `conventionalcommits`, and maybe we can also use the default configuration for [releaseRules](https://github.com/semantic-release/commit-analyzer?tab=readme-ov-file#releaserule), right?

**Comment by msclock** [comment]
> only define the "no-release" scope

I explicitly write all available scopes to the configuration is bucause it is enough accessible for new comers.

**Comment by huxuan** [comment]
> I explicitly write all available scopes to the configuration is bucause it is enough accessible for new comers.

This approach is indeed more friendly to new maintainers, but considering the increasing number of configurations for different tools, I suggest using the default configuration as much as possible with minimal cutomsization. Otherwise, we will end up with a huge `pyproject.toml`. This is also why the `black` formatter has become so popular. We can provide more information abut the default configuation in the the documentation for explanation.

Regarding the semantic-release configuration specifically, the idea came to me when I suddenly [realized](https://github.com/serious-scaffold/ss-python/pull/608#issuecomment-2198000703) that I had mistakenly configured `refactor` for patch release, while the default configuration only releases on `feat`, `fix`, `perf` and `revert` (I might have mixed up `revert` and `refactor`). As mentioned in #617, the release should be treated more seriously, so I suggest disabling the releases on `refactor`.

**Comment by msclock** [comment]
> disabling the releases on refactor

Yep, it is more reasonable, especially for loose stable main/master branch release.
